#!/usr/bin/env tsx
/**
 * Script to complete the 100-city dataset
 * Adds remaining cities to reach exactly 100 cities
 */

import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

// Remaining cities to reach 100 total
const remainingCities = [
  // European Cities
  {
    name: "Vienna",
    country: "Austria",
    region: "Vienna",
    latitude: 48.2082,
    longitude: 16.3738,
    population: 1911191,
    timezone: "Europe/Vienna",
    costOfLiving: 1300,
    internetSpeed: 89.1,
    safetyRating: 8.5,
    walkability: 8.5,
    nightlife: 7.5,
    culture: 9.5,
    weather: 6.5,
    description:
      "Vienna offers imperial architecture, excellent coffee culture, and high quality of life. The city has growing tech scene and central European location.",
    shortDescription: "Imperial architecture with excellent coffee culture",
    featured: false,
    verified: true,
  },
  {
    name: "Munich",
    country: "Germany",
    region: "Bavaria",
    latitude: 48.1351,
    longitude: 11.582,
    population: 1488202,
    timezone: "Europe/Berlin",
    costOfLiving: 1600,
    internetSpeed: 92.3,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 8.0,
    culture: 8.5,
    weather: 6.5,
    description:
      "Munich offers Bavarian culture, excellent beer, and strong tech scene. The city has beautiful Alpine proximity and high quality of life.",
    shortDescription: "Bavarian culture with excellent beer and tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Frankfurt",
    country: "Germany",
    region: "Hesse",
    latitude: 50.1109,
    longitude: 8.6821,
    population: 753056,
    timezone: "Europe/Berlin",
    costOfLiving: 1500,
    internetSpeed: 88.7,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 7.5,
    weather: 6.0,
    description:
      "Frankfurt is Germany's financial capital with excellent infrastructure and international atmosphere.",
    shortDescription:
      "Germany's financial capital with international atmosphere",
    featured: false,
    verified: true,
  },
  {
    name: "Zurich",
    country: "Switzerland",
    region: "Zurich",
    latitude: 47.3769,
    longitude: 8.5417,
    population: 415367,
    timezone: "Europe/Zurich",
    costOfLiving: 2800,
    internetSpeed: 156.8,
    safetyRating: 9.0,
    walkability: 8.5,
    nightlife: 6.5,
    culture: 8.0,
    weather: 6.5,
    description:
      "Zurich offers world-class infrastructure, excellent safety, and high salaries. Strong fintech scene.",
    shortDescription: "World-class infrastructure with strong fintech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Stockholm",
    country: "Sweden",
    region: "Stockholm County",
    latitude: 59.3293,
    longitude: 18.0686,
    population: 975551,
    timezone: "Europe/Stockholm",
    costOfLiving: 1800,
    internetSpeed: 126.7,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 8.5,
    weather: 5.5,
    description:
      "Stockholm is built on 14 islands with excellent tech scene and innovative culture.",
    shortDescription: "Built on 14 islands with excellent tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Copenhagen",
    country: "Denmark",
    region: "Capital Region",
    latitude: 55.6761,
    longitude: 12.5683,
    population: 660193,
    timezone: "Europe/Copenhagen",
    costOfLiving: 1900,
    internetSpeed: 134.2,
    safetyRating: 8.5,
    walkability: 9.0,
    nightlife: 7.5,
    culture: 8.5,
    weather: 6.0,
    description:
      "Copenhagen offers bike-friendly culture, excellent design scene, and sustainability focus.",
    shortDescription: "Bike-friendly with excellent design scene",
    featured: false,
    verified: true,
  },
  {
    name: "Helsinki",
    country: "Finland",
    region: "Uusimaa",
    latitude: 60.1699,
    longitude: 24.9384,
    population: 658864,
    timezone: "Europe/Helsinki",
    costOfLiving: 1600,
    internetSpeed: 121.4,
    safetyRating: 9.0,
    walkability: 8.5,
    nightlife: 6.5,
    culture: 8.0,
    weather: 5.0,
    description:
      "Helsinki offers excellent quality of life and innovative tech scene.",
    shortDescription: "Excellent quality of life with innovative tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Oslo",
    country: "Norway",
    region: "Oslo",
    latitude: 59.9139,
    longitude: 10.7522,
    population: 697549,
    timezone: "Europe/Oslo",
    costOfLiving: 2200,
    internetSpeed: 142.8,
    safetyRating: 9.0,
    walkability: 8.0,
    nightlife: 6.5,
    culture: 8.0,
    weather: 5.5,
    description:
      "Oslo offers stunning nature access and excellent quality of life.",
    shortDescription: "Stunning nature access with excellent quality of life",
    featured: false,
    verified: true,
  },
  {
    name: "Dublin",
    country: "Ireland",
    region: "Leinster",
    latitude: 53.3498,
    longitude: -6.2603,
    population: 1388000,
    timezone: "Europe/Dublin",
    costOfLiving: 1700,
    internetSpeed: 97.4,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 8.5,
    culture: 9.0,
    weather: 6.0,
    description:
      "Dublin offers rich literary culture, friendly locals, and growing tech scene.",
    shortDescription: "Rich literary culture with friendly locals",
    featured: false,
    verified: true,
  },
  {
    name: "London",
    country: "United Kingdom",
    region: "Greater London",
    latitude: 51.5074,
    longitude: -0.1278,
    population: 9648110,
    timezone: "Europe/London",
    costOfLiving: 2500,
    internetSpeed: 78.9,
    safetyRating: 7.0,
    walkability: 8.0,
    nightlife: 9.0,
    culture: 9.5,
    weather: 5.5,
    description:
      "London is a global financial and tech hub with unmatched cultural offerings.",
    shortDescription: "Global financial and tech hub with unmatched culture",
    featured: false,
    verified: true,
  },
  {
    name: "Edinburgh",
    country: "United Kingdom",
    region: "Scotland",
    latitude: 55.9533,
    longitude: -3.1883,
    population: 518500,
    timezone: "Europe/London",
    costOfLiving: 1500,
    internetSpeed: 89.6,
    safetyRating: 8.5,
    walkability: 8.5,
    nightlife: 7.5,
    culture: 9.0,
    weather: 5.5,
    description:
      "Edinburgh offers stunning medieval architecture and vibrant festival culture.",
    shortDescription: "Stunning medieval architecture with festival culture",
    featured: false,
    verified: true,
  },
  {
    name: "Paris",
    country: "France",
    region: "Île-de-France",
    latitude: 48.8566,
    longitude: 2.3522,
    population: 2161000,
    timezone: "Europe/Paris",
    costOfLiving: 1900,
    internetSpeed: 85.7,
    safetyRating: 6.5,
    walkability: 8.5,
    nightlife: 8.5,
    culture: 9.5,
    weather: 6.5,
    description:
      "Paris offers unmatched culture, cuisine, and architecture with growing tech scene.",
    shortDescription: "Unmatched culture and cuisine with growing tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Lyon",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    latitude: 45.764,
    longitude: 4.8357,
    population: 518635,
    timezone: "Europe/Paris",
    costOfLiving: 1400,
    internetSpeed: 78.2,
    safetyRating: 7.5,
    walkability: 8.0,
    nightlife: 7.5,
    culture: 8.5,
    weather: 7.0,
    description:
      "Lyon offers excellent cuisine and more affordable costs than Paris.",
    shortDescription: "Excellent cuisine with affordable costs",
    featured: false,
    verified: true,
  },
  {
    name: "Nice",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    latitude: 43.7102,
    longitude: 7.262,
    population: 342637,
    timezone: "Europe/Paris",
    costOfLiving: 1600,
    internetSpeed: 72.8,
    safetyRating: 7.0,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 8.0,
    weather: 8.5,
    description: "Nice offers Mediterranean lifestyle and beautiful beaches.",
    shortDescription: "Mediterranean lifestyle with beautiful beaches",
    featured: false,
    verified: true,
  },
  {
    name: "Milan",
    country: "Italy",
    region: "Lombardy",
    latitude: 45.4642,
    longitude: 9.19,
    population: 1396059,
    timezone: "Europe/Rome",
    costOfLiving: 1500,
    internetSpeed: 67.4,
    safetyRating: 7.0,
    walkability: 8.0,
    nightlife: 8.0,
    culture: 9.0,
    weather: 7.0,
    description:
      "Milan is Italy's economic capital with fashion and design focus.",
    shortDescription: "Italy's economic capital with fashion focus",
    featured: false,
    verified: true,
  },
  {
    name: "Rome",
    country: "Italy",
    region: "Lazio",
    latitude: 41.9028,
    longitude: 12.4964,
    population: 2872800,
    timezone: "Europe/Rome",
    costOfLiving: 1300,
    internetSpeed: 58.9,
    safetyRating: 6.5,
    walkability: 7.5,
    nightlife: 8.0,
    culture: 10.0,
    weather: 7.5,
    description: "Rome offers unmatched history and incredible cuisine.",
    shortDescription: "Unmatched history with incredible cuisine",
    featured: false,
    verified: true,
  },
  {
    name: "Florence",
    country: "Italy",
    region: "Tuscany",
    latitude: 43.7696,
    longitude: 11.2558,
    population: 382258,
    timezone: "Europe/Rome",
    costOfLiving: 1200,
    internetSpeed: 62.1,
    safetyRating: 8.0,
    walkability: 9.0,
    nightlife: 7.0,
    culture: 9.5,
    weather: 7.5,
    description: "Florence offers Renaissance art and beautiful architecture.",
    shortDescription: "Renaissance art with beautiful architecture",
    featured: false,
    verified: true,
  },
  {
    name: "Porto",
    country: "Portugal",
    region: "Porto District",
    latitude: 41.1579,
    longitude: -8.6291,
    population: 237591,
    timezone: "Europe/Lisbon",
    costOfLiving: 900,
    internetSpeed: 78.9,
    safetyRating: 8.5,
    walkability: 8.5,
    nightlife: 7.5,
    culture: 9.0,
    weather: 8.0,
    description:
      "Porto offers beautiful architecture and excellent wine culture.",
    shortDescription: "Beautiful architecture with wine culture",
    featured: false,
    verified: true,
  },
  {
    name: "Madrid",
    country: "Spain",
    region: "Community of Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
    population: 3223334,
    timezone: "Europe/Madrid",
    costOfLiving: 1200,
    internetSpeed: 82.1,
    safetyRating: 7.5,
    walkability: 8.0,
    nightlife: 9.5,
    culture: 9.0,
    weather: 7.5,
    description: "Madrid offers vibrant culture and excellent nightlife.",
    shortDescription: "Vibrant culture with excellent nightlife",
    featured: false,
    verified: true,
  },
  {
    name: "Valencia",
    country: "Spain",
    region: "Valencian Community",
    latitude: 39.4699,
    longitude: -0.3763,
    population: 791413,
    timezone: "Europe/Madrid",
    costOfLiving: 1000,
    internetSpeed: 75.6,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 8.0,
    culture: 8.5,
    weather: 8.5,
    description: "Valencia offers Mediterranean beaches and excellent weather.",
    shortDescription: "Mediterranean beaches with excellent weather",
    featured: false,
    verified: true,
  },
  // Asian Cities
  {
    name: "Tokyo",
    country: "Japan",
    region: "Tokyo",
    latitude: 35.6762,
    longitude: 139.6503,
    population: 37400068,
    timezone: "Asia/Tokyo",
    costOfLiving: 2000,
    internetSpeed: 189.4,
    safetyRating: 9.5,
    walkability: 8.5,
    nightlife: 8.0,
    culture: 9.5,
    weather: 6.5,
    description:
      "Tokyo offers cutting-edge technology, incredible culture, and excellent safety.",
    shortDescription: "Cutting-edge technology with incredible culture",
    featured: false,
    verified: true,
  },
  {
    name: "Seoul",
    country: "South Korea",
    region: "Seoul",
    latitude: 37.5665,
    longitude: 126.978,
    population: 9776000,
    timezone: "Asia/Seoul",
    costOfLiving: 1400,
    internetSpeed: 245.5,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 9.0,
    culture: 9.0,
    weather: 6.0,
    description:
      "Seoul offers ultra-fast internet, vibrant culture, and excellent tech scene.",
    shortDescription: "Ultra-fast internet with vibrant culture",
    featured: false,
    verified: true,
  },
  {
    name: "Taipei",
    country: "Taiwan",
    region: "Taipei",
    latitude: 25.033,
    longitude: 121.5654,
    population: 2646204,
    timezone: "Asia/Taipei",
    costOfLiving: 1100,
    internetSpeed: 135.8,
    safetyRating: 9.0,
    walkability: 8.5,
    nightlife: 7.5,
    culture: 8.5,
    weather: 7.0,
    description:
      "Taipei offers excellent safety, great food, and affordable living.",
    shortDescription: "Excellent safety with great food and affordability",
    featured: false,
    verified: true,
  },
  {
    name: "Hong Kong",
    country: "Hong Kong",
    region: "Hong Kong",
    latitude: 22.3193,
    longitude: 114.1694,
    population: 7496981,
    timezone: "Asia/Hong_Kong",
    costOfLiving: 2300,
    internetSpeed: 254.4,
    safetyRating: 8.0,
    walkability: 8.5,
    nightlife: 8.5,
    culture: 8.0,
    weather: 7.0,
    description:
      "Hong Kong offers world-class infrastructure and business opportunities.",
    shortDescription: "World-class infrastructure with business opportunities",
    featured: false,
    verified: true,
  },
  {
    name: "Manila",
    country: "Philippines",
    region: "Metro Manila",
    latitude: 14.5995,
    longitude: 120.9842,
    population: 13482462,
    timezone: "Asia/Manila",
    costOfLiving: 650,
    internetSpeed: 85.2,
    safetyRating: 6.0,
    walkability: 5.5,
    nightlife: 8.0,
    culture: 8.0,
    weather: 7.5,
    description: "Manila offers very affordable costs and English proficiency.",
    shortDescription: "Very affordable with English proficiency",
    featured: false,
    verified: true,
  },
  {
    name: "Jakarta",
    country: "Indonesia",
    region: "Jakarta",
    latitude: -6.2088,
    longitude: 106.8456,
    population: 10770487,
    timezone: "Asia/Jakarta",
    costOfLiving: 700,
    internetSpeed: 54.3,
    safetyRating: 6.5,
    walkability: 5.0,
    nightlife: 7.5,
    culture: 8.0,
    weather: 7.0,
    description: "Jakarta offers affordable living and growing tech scene.",
    shortDescription: "Affordable living with growing tech scene",
    featured: false,
    verified: true,
  },
  // American Cities
  {
    name: "New York City",
    country: "United States",
    region: "New York",
    latitude: 40.7128,
    longitude: -74.006,
    population: 8336817,
    timezone: "America/New_York",
    costOfLiving: 3500,
    internetSpeed: 180.9,
    safetyRating: 6.5,
    walkability: 9.0,
    nightlife: 9.5,
    culture: 9.5,
    weather: 6.0,
    description: "NYC offers unmatched opportunities and cultural diversity.",
    shortDescription: "Unmatched opportunities with cultural diversity",
    featured: false,
    verified: true,
  },
  {
    name: "San Francisco",
    country: "United States",
    region: "California",
    latitude: 37.7749,
    longitude: -122.4194,
    population: 873965,
    timezone: "America/Los_Angeles",
    costOfLiving: 4000,
    internetSpeed: 198.7,
    safetyRating: 6.0,
    walkability: 8.5,
    nightlife: 7.5,
    culture: 8.5,
    weather: 8.0,
    description:
      "San Francisco is the global tech capital with innovation culture.",
    shortDescription: "Global tech capital with innovation culture",
    featured: false,
    verified: true,
  },
  {
    name: "Los Angeles",
    country: "United States",
    region: "California",
    latitude: 34.0522,
    longitude: -118.2437,
    population: 3898747,
    timezone: "America/Los_Angeles",
    costOfLiving: 3200,
    internetSpeed: 167.3,
    safetyRating: 6.0,
    walkability: 6.0,
    nightlife: 8.5,
    culture: 8.5,
    weather: 9.0,
    description:
      "LA offers entertainment industry connections and great weather.",
    shortDescription: "Entertainment industry with great weather",
    featured: false,
    verified: true,
  },
  {
    name: "Austin",
    country: "United States",
    region: "Texas",
    latitude: 30.2672,
    longitude: -97.7431,
    population: 978908,
    timezone: "America/Chicago",
    costOfLiving: 2200,
    internetSpeed: 156.4,
    safetyRating: 7.0,
    walkability: 6.5,
    nightlife: 8.5,
    culture: 8.0,
    weather: 7.0,
    description: "Austin offers vibrant tech scene and music culture.",
    shortDescription: "Vibrant tech scene with music culture",
    featured: false,
    verified: true,
  },
  {
    name: "Miami",
    country: "United States",
    region: "Florida",
    latitude: 25.7617,
    longitude: -80.1918,
    population: 467963,
    timezone: "America/New_York",
    costOfLiving: 2800,
    internetSpeed: 145.2,
    safetyRating: 6.5,
    walkability: 7.0,
    nightlife: 9.5,
    culture: 8.0,
    weather: 8.5,
    description: "Miami offers tropical lifestyle and growing tech scene.",
    shortDescription: "Tropical lifestyle with growing tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Toronto",
    country: "Canada",
    region: "Ontario",
    latitude: 43.6532,
    longitude: -79.3832,
    population: 2794356,
    timezone: "America/Toronto",
    costOfLiving: 2000,
    internetSpeed: 134.7,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 8.0,
    culture: 8.5,
    weather: 5.5,
    description:
      "Toronto offers multicultural environment and strong tech scene.",
    shortDescription: "Multicultural environment with strong tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Vancouver",
    country: "Canada",
    region: "British Columbia",
    latitude: 49.2827,
    longitude: -123.1207,
    population: 675218,
    timezone: "America/Vancouver",
    costOfLiving: 2200,
    internetSpeed: 142.8,
    safetyRating: 8.5,
    walkability: 8.5,
    nightlife: 7.0,
    culture: 8.0,
    weather: 7.0,
    description: "Vancouver offers stunning nature and high quality of life.",
    shortDescription: "Stunning nature with high quality of life",
    featured: false,
    verified: true,
  },
  {
    name: "São Paulo",
    country: "Brazil",
    region: "São Paulo",
    latitude: -23.5505,
    longitude: -46.6333,
    population: 12325232,
    timezone: "America/Sao_Paulo",
    costOfLiving: 800,
    internetSpeed: 67.8,
    safetyRating: 5.5,
    walkability: 6.5,
    nightlife: 9.0,
    culture: 8.5,
    weather: 7.0,
    description: "São Paulo offers vibrant culture and growing tech scene.",
    shortDescription: "Vibrant culture with growing tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Rio de Janeiro",
    country: "Brazil",
    region: "Rio de Janeiro",
    latitude: -22.9068,
    longitude: -43.1729,
    population: 6748000,
    timezone: "America/Sao_Paulo",
    costOfLiving: 750,
    internetSpeed: 58.9,
    safetyRating: 5.0,
    walkability: 7.0,
    nightlife: 9.5,
    culture: 9.0,
    weather: 8.5,
    description: "Rio offers stunning beaches and vibrant culture.",
    shortDescription: "Stunning beaches with vibrant culture",
    featured: false,
    verified: true,
  },
  {
    name: "Lima",
    country: "Peru",
    region: "Lima",
    latitude: -12.0464,
    longitude: -77.0428,
    population: 10092000,
    timezone: "America/Lima",
    costOfLiving: 650,
    internetSpeed: 45.7,
    safetyRating: 6.0,
    walkability: 6.0,
    nightlife: 7.5,
    culture: 8.5,
    weather: 7.5,
    description: "Lima offers rich history and excellent cuisine.",
    shortDescription: "Rich history with excellent cuisine",
    featured: false,
    verified: true,
  },
  {
    name: "Santiago",
    country: "Chile",
    region: "Santiago Metropolitan",
    latitude: -33.4489,
    longitude: -70.6693,
    population: 6257516,
    timezone: "America/Santiago",
    costOfLiving: 900,
    internetSpeed: 78.4,
    safetyRating: 7.0,
    walkability: 7.0,
    nightlife: 7.5,
    culture: 7.5,
    weather: 7.5,
    description: "Santiago offers mountain views and growing tech scene.",
    shortDescription: "Mountain views with growing tech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Montevideo",
    country: "Uruguay",
    region: "Montevideo",
    latitude: -34.9011,
    longitude: -56.1645,
    population: 1319108,
    timezone: "America/Montevideo",
    costOfLiving: 800,
    internetSpeed: 89.2,
    safetyRating: 7.5,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 7.5,
    weather: 7.0,
    description: "Montevideo offers excellent safety and quality of life.",
    shortDescription: "Excellent safety with quality of life",
    featured: false,
    verified: true,
  },
  // African Cities
  {
    name: "Marrakech",
    country: "Morocco",
    region: "Marrakech-Safi",
    latitude: 31.6295,
    longitude: -7.9811,
    population: 928850,
    timezone: "Africa/Casablanca",
    costOfLiving: 500,
    internetSpeed: 34.8,
    safetyRating: 7.0,
    walkability: 7.5,
    nightlife: 6.5,
    culture: 9.0,
    weather: 8.0,
    description: "Marrakech offers rich culture and very affordable living.",
    shortDescription: "Rich culture with very affordable living",
    featured: false,
    verified: true,
  },
  {
    name: "Cairo",
    country: "Egypt",
    region: "Cairo Governorate",
    latitude: 30.0444,
    longitude: 31.2357,
    population: 20484965,
    timezone: "Africa/Cairo",
    costOfLiving: 400,
    internetSpeed: 31.9,
    safetyRating: 6.0,
    walkability: 6.0,
    nightlife: 6.5,
    culture: 9.5,
    weather: 7.0,
    description: "Cairo offers ancient history and very low costs.",
    shortDescription: "Ancient history with very low costs",
    featured: false,
    verified: true,
  },
  {
    name: "Nairobi",
    country: "Kenya",
    region: "Nairobi County",
    latitude: -1.2921,
    longitude: 36.8219,
    population: 4397073,
    timezone: "Africa/Nairobi",
    costOfLiving: 600,
    internetSpeed: 25.4,
    safetyRating: 5.5,
    walkability: 5.0,
    nightlife: 7.0,
    culture: 7.5,
    weather: 8.5,
    description: "Nairobi offers growing tech scene and excellent weather.",
    shortDescription: "Growing tech scene with excellent weather",
    featured: false,
    verified: true,
  },
  // Oceania Cities
  {
    name: "Sydney",
    country: "Australia",
    region: "New South Wales",
    latitude: -33.8688,
    longitude: 151.2093,
    population: 5312163,
    timezone: "Australia/Sydney",
    costOfLiving: 2400,
    internetSpeed: 89.7,
    safetyRating: 8.5,
    walkability: 7.5,
    nightlife: 8.0,
    culture: 8.0,
    weather: 8.5,
    description:
      "Sydney offers beautiful harbor and excellent quality of life.",
    shortDescription: "Beautiful harbor with excellent quality of life",
    featured: false,
    verified: true,
  },
  {
    name: "Melbourne",
    country: "Australia",
    region: "Victoria",
    latitude: -37.8136,
    longitude: 144.9631,
    population: 5078193,
    timezone: "Australia/Melbourne",
    costOfLiving: 2200,
    internetSpeed: 87.4,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 8.5,
    culture: 9.0,
    weather: 7.0,
    description: "Melbourne offers excellent coffee culture and arts scene.",
    shortDescription: "Excellent coffee culture with arts scene",
    featured: false,
    verified: true,
  },
  {
    name: "Auckland",
    country: "New Zealand",
    region: "Auckland",
    latitude: -36.8485,
    longitude: 174.7633,
    population: 1695200,
    timezone: "Pacific/Auckland",
    costOfLiving: 2000,
    internetSpeed: 95.3,
    safetyRating: 9.0,
    walkability: 7.0,
    nightlife: 7.0,
    culture: 7.5,
    weather: 7.5,
    description: "Auckland offers excellent safety and stunning nature.",
    shortDescription: "Excellent safety with stunning nature",
    featured: false,
    verified: true,
  },
];

// Main function to complete the 100-city dataset
async function complete100Cities() {
  try {
    console.log("🎯 Completing 100-city dataset...");

    // Check current count
    const currentCount = await prisma.city.count();
    console.log(`📊 Current cities in database: ${currentCount}`);

    if (currentCount >= 100) {
      console.log("✅ Database already has 100+ cities!");
      return;
    }

    // Calculate how many more cities we need
    const needed = 100 - currentCount;
    const citiesToAdd = remainingCities.slice(0, needed);

    console.log(`📍 Adding ${citiesToAdd.length} cities to reach 100...`);

    // Insert in batches
    const batchSize = 10;
    let inserted = 0;

    for (let i = 0; i < citiesToAdd.length; i += batchSize) {
      const batch = citiesToAdd.slice(i, i + batchSize);

      await prisma.city.createMany({
        data: batch,
        skipDuplicates: true,
      });

      inserted += batch.length;
      console.log(`✅ Inserted ${inserted}/${citiesToAdd.length} cities`);
    }

    // Final verification
    const finalCount = await prisma.city.count();
    console.log(`🎉 Dataset completed! Total cities: ${finalCount}`);

    // Statistics
    const featured = await prisma.city.count({ where: { featured: true } });
    const verified = await prisma.city.count({ where: { verified: true } });
    const countries = await prisma.city.groupBy({
      by: ["country"],
      _count: { country: true },
    });

    console.log(`⭐ Featured cities: ${featured}`);
    console.log(`✅ Verified cities: ${verified}`);
    console.log(`🌍 Countries represented: ${countries.length}`);
  } catch (error) {
    console.error("❌ Error completing dataset:", error);
    throw error;
  }
}

// Main execution
async function main() {
  try {
    await complete100Cities();
    console.log("🎉 100-city dataset completion successful!");
  } catch (error) {
    console.error("💥 Failed to complete dataset:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Run the script
if (require.main === module) {
  main().catch(console.error);
}

export { remainingCities, complete100Cities };
