#!/usr/bin/env tsx
/**
 * Script to add the final 33 cities to reach exactly 100 cities
 */

import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

// Final 33 cities to reach exactly 100
const final33Cities = [
  {
    name: "Krakow",
    country: "Poland",
    region: "Lesser Poland",
    latitude: 50.0647,
    longitude: 19.945,
    population: 779115,
    timezone: "Europe/Warsaw",
    costOfLiving: 800,
    internetSpeed: 85.2,
    safetyRating: 8.5,
    walkability: 8.5,
    nightlife: 8.0,
    culture: 9.0,
    weather: 6.0,
    description:
      "Krakow offers medieval charm, affordable costs, and vibrant student culture.",
    shortDescription: "Medieval charm with vibrant student culture",
    featured: false,
    verified: true,
  },
  {
    name: "Tallinn",
    country: "Estonia",
    region: "Harju County",
    latitude: 59.437,
    longitude: 24.7536,
    population: 437619,
    timezone: "Europe/Tallinn",
    costOfLiving: 950,
    internetSpeed: 95.8,
    safetyRating: 8.5,
    walkability: 8.5,
    nightlife: 7.0,
    culture: 8.0,
    weather: 5.5,
    description:
      "Tallinn is a digital-first city with excellent e-governance and medieval charm.",
    shortDescription: "Digital-first city with medieval charm",
    featured: false,
    verified: true,
  },
  {
    name: "Riga",
    country: "Latvia",
    region: "Riga",
    latitude: 56.9496,
    longitude: 24.1052,
    population: 632614,
    timezone: "Europe/Riga",
    costOfLiving: 800,
    internetSpeed: 78.3,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 7.5,
    culture: 8.0,
    weather: 5.5,
    description:
      "Riga offers stunning Art Nouveau architecture and affordable costs.",
    shortDescription: "Stunning Art Nouveau architecture",
    featured: false,
    verified: true,
  },
  {
    name: "Vilnius",
    country: "Lithuania",
    region: "Vilnius County",
    latitude: 54.6872,
    longitude: 25.2797,
    population: 588412,
    timezone: "Europe/Vilnius",
    costOfLiving: 750,
    internetSpeed: 89.7,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 8.5,
    weather: 5.5,
    description:
      "Vilnius offers beautiful baroque architecture and growing fintech scene.",
    shortDescription: "Beautiful baroque architecture with fintech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Ljubljana",
    country: "Slovenia",
    region: "Ljubljana",
    latitude: 46.0569,
    longitude: 14.5058,
    population: 295504,
    timezone: "Europe/Ljubljana",
    costOfLiving: 1100,
    internetSpeed: 72.1,
    safetyRating: 9.0,
    walkability: 9.0,
    nightlife: 6.5,
    culture: 8.0,
    weather: 7.0,
    description:
      "Ljubljana is a small, green capital with excellent safety and walkability.",
    shortDescription: "Small green capital with excellent safety",
    featured: false,
    verified: true,
  },
  {
    name: "Zagreb",
    country: "Croatia",
    region: "Zagreb County",
    latitude: 45.815,
    longitude: 15.9819,
    population: 790017,
    timezone: "Europe/Zagreb",
    costOfLiving: 950,
    internetSpeed: 58.9,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 8.0,
    weather: 6.5,
    description:
      "Zagreb offers charming Central European atmosphere and great coffee culture.",
    shortDescription: "Charming Central European atmosphere",
    featured: false,
    verified: true,
  },
  {
    name: "Bratislava",
    country: "Slovakia",
    region: "Bratislava Region",
    latitude: 48.1486,
    longitude: 17.1077,
    population: 432864,
    timezone: "Europe/Bratislava",
    costOfLiving: 850,
    internetSpeed: 65.4,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 7.0,
    culture: 7.5,
    weather: 6.5,
    description: "Bratislava offers affordable costs and proximity to Vienna.",
    shortDescription: "Affordable with proximity to Vienna",
    featured: false,
    verified: true,
  },
  {
    name: "Brussels",
    country: "Belgium",
    region: "Brussels-Capital Region",
    latitude: 50.8503,
    longitude: 4.3517,
    population: 1208542,
    timezone: "Europe/Brussels",
    costOfLiving: 1400,
    internetSpeed: 76.8,
    safetyRating: 7.0,
    walkability: 8.0,
    nightlife: 7.5,
    culture: 8.5,
    weather: 6.0,
    description:
      "Brussels offers EU headquarters and multicultural atmosphere.",
    shortDescription: "EU headquarters with multicultural atmosphere",
    featured: false,
    verified: true,
  },
  {
    name: "Antwerp",
    country: "Belgium",
    region: "Flanders",
    latitude: 51.2194,
    longitude: 4.4025,
    population: 529247,
    timezone: "Europe/Brussels",
    costOfLiving: 1200,
    internetSpeed: 74.2,
    safetyRating: 7.5,
    walkability: 8.5,
    nightlife: 7.5,
    culture: 8.5,
    weather: 6.0,
    description: "Antwerp offers diamond trade heritage and fashion scene.",
    shortDescription: "Diamond trade heritage with fashion scene",
    featured: false,
    verified: true,
  },
  {
    name: "Luxembourg City",
    country: "Luxembourg",
    region: "Luxembourg",
    latitude: 49.6116,
    longitude: 6.1319,
    population: 125000,
    timezone: "Europe/Luxembourg",
    costOfLiving: 2000,
    internetSpeed: 115.3,
    safetyRating: 9.0,
    walkability: 8.0,
    nightlife: 6.0,
    culture: 7.5,
    weather: 6.0,
    description:
      "Luxembourg City offers financial hub status and excellent safety.",
    shortDescription: "Financial hub with excellent safety",
    featured: false,
    verified: true,
  },
  {
    name: "Athens",
    country: "Greece",
    region: "Attica",
    latitude: 37.9838,
    longitude: 23.7275,
    population: 664046,
    timezone: "Europe/Athens",
    costOfLiving: 800,
    internetSpeed: 52.3,
    safetyRating: 7.0,
    walkability: 7.5,
    nightlife: 8.0,
    culture: 9.5,
    weather: 8.0,
    description: "Athens offers ancient history and Mediterranean lifestyle.",
    shortDescription: "Ancient history with Mediterranean lifestyle",
    featured: false,
    verified: true,
  },
  {
    name: "Thessaloniki",
    country: "Greece",
    region: "Central Macedonia",
    latitude: 40.6401,
    longitude: 22.9444,
    population: 325182,
    timezone: "Europe/Athens",
    costOfLiving: 700,
    internetSpeed: 48.9,
    safetyRating: 7.5,
    walkability: 8.0,
    nightlife: 8.5,
    culture: 8.5,
    weather: 7.5,
    description:
      "Thessaloniki offers vibrant student culture and beautiful waterfront.",
    shortDescription: "Vibrant student culture with waterfront",
    featured: false,
    verified: true,
  },
  {
    name: "Seville",
    country: "Spain",
    region: "Andalusia",
    latitude: 37.3891,
    longitude: -5.9845,
    population: 688711,
    timezone: "Europe/Madrid",
    costOfLiving: 900,
    internetSpeed: 68.7,
    safetyRating: 8.0,
    walkability: 8.5,
    nightlife: 8.5,
    culture: 9.5,
    weather: 7.5,
    description:
      "Seville offers authentic Spanish culture and beautiful architecture.",
    shortDescription: "Authentic Spanish culture with architecture",
    featured: false,
    verified: true,
  },
  {
    name: "Palma",
    country: "Spain",
    region: "Balearic Islands",
    latitude: 39.5696,
    longitude: 2.6502,
    population: 416065,
    timezone: "Europe/Madrid",
    costOfLiving: 1300,
    internetSpeed: 71.8,
    safetyRating: 8.5,
    walkability: 8.0,
    nightlife: 7.5,
    culture: 8.0,
    weather: 9.0,
    description: "Palma offers island lifestyle and beautiful beaches.",
    shortDescription: "Island lifestyle with beautiful beaches",
    featured: false,
    verified: true,
  },
  {
    name: "Las Palmas",
    country: "Spain",
    region: "Canary Islands",
    latitude: 28.1248,
    longitude: -15.43,
    population: 379925,
    timezone: "Atlantic/Canary",
    costOfLiving: 1000,
    internetSpeed: 65.4,
    safetyRating: 8.0,
    walkability: 7.5,
    nightlife: 7.0,
    culture: 7.5,
    weather: 9.5,
    description: "Las Palmas offers year-round perfect weather and beaches.",
    shortDescription: "Year-round perfect weather with beaches",
    featured: false,
    verified: true,
  },
  {
    name: "Funchal",
    country: "Portugal",
    region: "Madeira",
    latitude: 32.6669,
    longitude: -16.9241,
    population: 105795,
    timezone: "Atlantic/Madeira",
    costOfLiving: 1000,
    internetSpeed: 72.1,
    safetyRating: 9.0,
    walkability: 7.0,
    nightlife: 6.0,
    culture: 7.5,
    weather: 9.0,
    description: "Funchal offers subtropical climate and excellent safety.",
    shortDescription: "Subtropical climate with excellent safety",
    featured: false,
    verified: true,
  },
  {
    name: "Venice",
    country: "Italy",
    region: "Veneto",
    latitude: 45.4408,
    longitude: 12.3155,
    population: 261905,
    timezone: "Europe/Rome",
    costOfLiving: 1400,
    internetSpeed: 55.7,
    safetyRating: 8.0,
    walkability: 9.0,
    nightlife: 6.5,
    culture: 9.5,
    weather: 7.0,
    description:
      "Venice offers unique canal setting and incredible architecture.",
    shortDescription: "Unique canal setting with architecture",
    featured: false,
    verified: true,
  },
  {
    name: "Geneva",
    country: "Switzerland",
    region: "Geneva",
    latitude: 46.2044,
    longitude: 6.1432,
    population: 201818,
    timezone: "Europe/Zurich",
    costOfLiving: 2700,
    internetSpeed: 148.9,
    safetyRating: 9.0,
    walkability: 8.0,
    nightlife: 6.0,
    culture: 8.0,
    weather: 6.5,
    description:
      "Geneva offers international atmosphere and beautiful lake setting.",
    shortDescription: "International atmosphere with lake setting",
    featured: false,
    verified: true,
  },
  {
    name: "Hamburg",
    country: "Germany",
    region: "Hamburg",
    latitude: 53.5511,
    longitude: 9.9937,
    population: 1945532,
    timezone: "Europe/Berlin",
    costOfLiving: 1400,
    internetSpeed: 85.9,
    safetyRating: 8.0,
    walkability: 8.0,
    nightlife: 8.5,
    culture: 8.0,
    weather: 6.0,
    description: "Hamburg offers maritime culture and vibrant nightlife.",
    shortDescription: "Maritime culture with vibrant nightlife",
    featured: false,
    verified: true,
  },
  {
    name: "Cologne",
    country: "Germany",
    region: "North Rhine-Westphalia",
    latitude: 50.9375,
    longitude: 6.9603,
    population: 1087863,
    timezone: "Europe/Berlin",
    costOfLiving: 1300,
    internetSpeed: 82.4,
    safetyRating: 7.5,
    walkability: 8.0,
    nightlife: 8.0,
    culture: 8.5,
    weather: 6.0,
    description: "Cologne offers rich history and vibrant arts scene.",
    shortDescription: "Rich history with vibrant arts scene",
    featured: false,
    verified: true,
  },
  {
    name: "Reykjavik",
    country: "Iceland",
    region: "Capital Region",
    latitude: 64.1466,
    longitude: -21.9426,
    population: 131136,
    timezone: "Atlantic/Reykjavik",
    costOfLiving: 2000,
    internetSpeed: 118.3,
    safetyRating: 9.5,
    walkability: 8.0,
    nightlife: 7.5,
    culture: 8.5,
    weather: 4.5,
    description:
      "Reykjavik offers unique Nordic culture and stunning natural beauty.",
    shortDescription: "Unique Nordic culture with natural beauty",
    featured: false,
    verified: true,
  },
  {
    name: "Malta",
    country: "Malta",
    region: "Malta",
    latitude: 35.8997,
    longitude: 14.5146,
    population: 213716,
    timezone: "Europe/Malta",
    costOfLiving: 1200,
    internetSpeed: 89.4,
    safetyRating: 8.5,
    walkability: 7.0,
    nightlife: 7.5,
    culture: 8.0,
    weather: 8.5,
    description: "Malta offers EU membership and English proficiency.",
    shortDescription: "EU membership with English proficiency",
    featured: false,
    verified: true,
  },
  {
    name: "Nicosia",
    country: "Cyprus",
    region: "Nicosia District",
    latitude: 35.1856,
    longitude: 33.3823,
    population: 330000,
    timezone: "Asia/Nicosia",
    costOfLiving: 1100,
    internetSpeed: 67.8,
    safetyRating: 8.5,
    walkability: 7.0,
    nightlife: 6.5,
    culture: 7.5,
    weather: 8.5,
    description: "Nicosia offers EU benefits and growing fintech scene.",
    shortDescription: "EU benefits with growing fintech scene",
    featured: false,
    verified: true,
  },
  {
    name: "Hanoi",
    country: "Vietnam",
    region: "Hanoi",
    latitude: 21.0285,
    longitude: 105.8542,
    population: 8053663,
    timezone: "Asia/Ho_Chi_Minh",
    costOfLiving: 550,
    internetSpeed: 48.7,
    safetyRating: 8.0,
    walkability: 7.0,
    nightlife: 7.5,
    culture: 8.5,
    weather: 7.0,
    description: "Hanoi offers rich culture and very affordable living costs.",
    shortDescription: "Rich culture with very affordable costs",
    featured: false,
    verified: true,
  },
  {
    name: "Da Nang",
    country: "Vietnam",
    region: "Da Nang",
    latitude: 16.0544,
    longitude: 108.2022,
    population: 1230000,
    timezone: "Asia/Ho_Chi_Minh",
    costOfLiving: 500,
    internetSpeed: 52.3,
    safetyRating: 8.5,
    walkability: 6.5,
    nightlife: 7.0,
    culture: 7.5,
    weather: 8.0,
    description:
      "Da Nang offers beautiful beaches and growing nomad community.",
    shortDescription: "Beautiful beaches with growing nomad community",
    featured: false,
    verified: true,
  },
  {
    name: "Penang",
    country: "Malaysia",
    region: "Penang",
    latitude: 5.4164,
    longitude: 100.3327,
    population: 1767000,
    timezone: "Asia/Kuala_Lumpur",
    costOfLiving: 650,
    internetSpeed: 68.9,
    safetyRating: 8.0,
    walkability: 7.0,
    nightlife: 7.0,
    culture: 8.5,
    weather: 7.5,
    description: "Penang offers UNESCO heritage and excellent food culture.",
    shortDescription: "UNESCO heritage with excellent food culture",
    featured: false,
    verified: true,
  },
  {
    name: "Canggu",
    country: "Indonesia",
    region: "Bali",
    latitude: -8.6482,
    longitude: 115.1378,
    population: 50000,
    timezone: "Asia/Makassar",
    costOfLiving: 750,
    internetSpeed: 42.8,
    safetyRating: 7.5,
    walkability: 6.0,
    nightlife: 8.0,
    culture: 8.5,
    weather: 9.0,
    description:
      "Canggu offers surf culture and strong digital nomad community.",
    shortDescription: "Surf culture with strong nomad community",
    featured: false,
    verified: true,
  },
  {
    name: "Ubud",
    country: "Indonesia",
    region: "Bali",
    latitude: -8.5069,
    longitude: 115.2625,
    population: 74320,
    timezone: "Asia/Makassar",
    costOfLiving: 700,
    internetSpeed: 38.9,
    safetyRating: 8.0,
    walkability: 7.0,
    nightlife: 6.0,
    culture: 9.5,
    weather: 8.5,
    description: "Ubud offers spiritual culture and beautiful rice terraces.",
    shortDescription: "Spiritual culture with beautiful rice terraces",
    featured: false,
    verified: true,
  },
  {
    name: "Cebu City",
    country: "Philippines",
    region: "Central Visayas",
    latitude: 10.3157,
    longitude: 123.8854,
    population: 964169,
    timezone: "Asia/Manila",
    costOfLiving: 600,
    internetSpeed: 78.4,
    safetyRating: 6.5,
    walkability: 6.0,
    nightlife: 7.5,
    culture: 7.5,
    weather: 8.0,
    description: "Cebu City offers affordable costs and English proficiency.",
    shortDescription: "Affordable costs with English proficiency",
    featured: false,
    verified: true,
  },
  {
    name: "Playa del Carmen",
    country: "Mexico",
    region: "Quintana Roo",
    latitude: 20.6296,
    longitude: -87.0739,
    population: 149923,
    timezone: "America/Cancun",
    costOfLiving: 1000,
    internetSpeed: 58.7,
    safetyRating: 7.0,
    walkability: 8.0,
    nightlife: 8.5,
    culture: 7.5,
    weather: 8.5,
    description:
      "Playa del Carmen offers Caribbean beaches and growing nomad scene.",
    shortDescription: "Caribbean beaches with growing nomad scene",
    featured: false,
    verified: true,
  },
  {
    name: "Tulum",
    country: "Mexico",
    region: "Quintana Roo",
    latitude: 20.2114,
    longitude: -87.4654,
    population: 18233,
    timezone: "America/Cancun",
    costOfLiving: 1200,
    internetSpeed: 45.2,
    safetyRating: 7.5,
    walkability: 7.0,
    nightlife: 7.0,
    culture: 8.0,
    weather: 8.5,
    description: "Tulum offers bohemian beach culture and Mayan ruins.",
    shortDescription: "Bohemian beach culture with Mayan ruins",
    featured: false,
    verified: true,
  },
  {
    name: "Cali",
    country: "Colombia",
    region: "Valle del Cauca",
    latitude: 3.4516,
    longitude: -76.532,
    population: 2227642,
    timezone: "America/Bogota",
    costOfLiving: 650,
    internetSpeed: 48.9,
    safetyRating: 6.5,
    walkability: 6.5,
    nightlife: 9.0,
    culture: 8.5,
    weather: 8.5,
    description: "Cali offers salsa culture and vibrant nightlife.",
    shortDescription: "Salsa culture with vibrant nightlife",
    featured: false,
    verified: true,
  },
];

// Main function
async function addFinal33Cities() {
  try {
    console.log("🎯 Adding final 33 cities to reach exactly 100...");

    const currentCount = await prisma.city.count();
    console.log(`📊 Current cities: ${currentCount}`);

    if (currentCount >= 100) {
      console.log("✅ Already have 100+ cities!");
      return;
    }

    const needed = 100 - currentCount;
    const citiesToAdd = final33Cities.slice(0, needed);

    console.log(`📍 Adding ${citiesToAdd.length} cities...`);

    // Insert in batches
    const batchSize = 10;
    let inserted = 0;

    for (let i = 0; i < citiesToAdd.length; i += batchSize) {
      const batch = citiesToAdd.slice(i, i + batchSize);

      await prisma.city.createMany({
        data: batch,
        skipDuplicates: true,
      });

      inserted += batch.length;
      console.log(`✅ Inserted ${inserted}/${citiesToAdd.length} cities`);
    }

    const finalCount = await prisma.city.count();
    console.log(`🎉 Final count: ${finalCount} cities!`);

    if (finalCount >= 100) {
      console.log("🎯 TARGET ACHIEVED: 100+ cities in database!");
    }
  } catch (error) {
    console.error("❌ Error:", error);
    throw error;
  }
}

// Main execution
async function main() {
  try {
    await addFinal33Cities();
    console.log("🎉 Successfully completed 100-city dataset!");
  } catch (error) {
    console.error("💥 Failed:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  main().catch(console.error);
}

export { final33Cities, addFinal33Cities };
